sudo: required
dist: bionic
language: cpp
compiler:
  - g++
before_install:
  - sudo apt-get install flex
  - sudo apt-get install googletest
  - sudo apt-get install librecode-dev
  - sudo apt-get install libsqlite3-dev
  - sudo apt-get install qtbase5-dev-tools
  - sudo apt-get install qttools5-dev-tools
  - sudo apt-get install qtbase5-dev
install:
  - ./autogen.sh
  - ./configure
  - make
script:
  - make check
